image: matthewfeickert/docker-python3-ubuntu

stages:
  - lint
  - pytest
  - test
  - push_result

pylint:
  stage: lint
  image: snakepacker/python:all
  before_script:
    - python3.12 -m pip install poetry
    - poetry install
  script:
    - poetry run pylint shortener tests

pytest:
  stage: pytest
  image: snakepacker/python:all
  services:
    - name: postgres
  variables:
    POSTGRES_DB: shortener_db
    POSTGRES_USER: master
    POSTGRES_PASSWORD: password
    POSTGRES_PORT: 5432
    POSTGRES_HOST: postgres
    DB_PATH: postgres
  before_script:
    - python3.12 -m pip install poetry
    - poetry install
    - wait-for-port postgres:5432
  script:
    - poetry run pytest --verbosity=2 --showlocals --log-level=DEBUG --cov=shortener

run_tests:
  retry: 2
  stage: test
  artifacts:
    paths:
      - score.json
      - REPO_NAME
  script:
    - printenv
    - python3 -m pip install requests
    - rm reporter.py
    - rm .gitlab-ci.yml
    - sudo apt-get update && sudo apt-get install -y gettext
    - python3 run_test.py "$REPO_NAME"
    - rm -rf .git

push_result:
  retry: 2
  dependencies:
    - run_tests
  stage: push_result
  script:
    - python3 -m pip install requests
    - python3 reporter.py
    - rm -rf .git

