"""create vip_links table

Revision ID: 140bc08b73bd
Revises: 4acb92a8f909
Create Date: 2024-06-18 16:13:24.042691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '140bc08b73bd'
down_revision = '4acb92a8f909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix__url_storage__long_url', table_name='url_storage')
    op.drop_index('ix__url_storage__secret_key', table_name='url_storage')
    op.drop_index('ix__url_storage__short_url', table_name='url_storage')
    op.drop_table('url_storage')
    # ### end Alembic commands ###
    
    # ### manually added commands ###
    op.create_table(
        'url_storage',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False, primary_key=True),
        sa.Column('vip_key', sa.TEXT(), nullable=True, unique=True, index=True),
        sa.Column('long_url', sa.TEXT(), nullable=False, index=True),
        sa.Column('short_url', sa.TEXT(), nullable=False, unique=True, index=True),
        sa.Column('secret_key', postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False, unique=True, index=True),
        sa.Column('number_of_clicks', sa.INTEGER(), server_default=sa.text("0"), nullable=False),
        sa.Column('dt_created', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    
    op.create_table(
        'vip_links',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False, primary_key=True),
        sa.Column('short_url', sa.TEXT(), nullable=False, unique=True, index=True),
        sa.Column('long_url', sa.TEXT(), nullable=False),
        sa.Column('secret_key', postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False, unique=True, index=True),
        sa.Column('ttl', sa.INTEGER(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    # ### end manually added commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_storage',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
        sa.Column('long_url', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('short_url', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('secret_key', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=True),
        sa.Column('number_of_clicks', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
        sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='pk__url_storage'),
        sa.UniqueConstraint('id', name='uq__url_storage__id')
    )
    op.create_index('ix__url_storage__short_url', 'url_storage', ['short_url'], unique=True)
    op.create_index('ix__url_storage__secret_key', 'url_storage', ['secret_key'], unique=True)
    op.create_index('ix__url_storage__long_url', 'url_storage', ['long_url'], unique=False)
    # ### end Alembic commands ###
    
    # ### manually added commands ###
    op.drop_table('vip_links')
    # ### end manually added commands ###

